version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_TAG: nyitus/rideout:latest
    docker:
      - image: docker:stable

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag "${IMAGE_TAG}" .
      - run:
          name: Archive Docker image
          command: docker save --output image.tar "${IMAGE_TAG}"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  push-docker-hub:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: docker load --input /tmp/workspace/image.tar
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$IMAGE_TAG"

  push-server:
    docker:
      - image: cibuilds/base
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run:
          name: Pull and run new image
          command: |
            echo "82.165.102.144 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGZxuVBzFj/F8+h6WkVtijSkQugblIaa5bvdyN6JAa9l6AEtTP0GWA0Iq0uS0M+VNC98TJrSnkTS+GA7Vy0x/NQ=" >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST <<'ENDSSH'
            docker pull $IMAGE_TAG
            docker stop rideout
            docker rm rideout
            docker run --name=my-app --restart=always -p 8010:8010 -d $IMAGE_TAG
            ENDSSH

workflows:
  version: 2
  build-push:
    jobs:
      - build
      - push-docker-hub:
          requires:
            - build
          filters:
            branches:
              only: main
      - push-server:
          requires:
            - push-docker-hub
          filters:
            branches:
              only: main