# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI. Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: tests

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      working-directory: ./src
      env:
        FIREBASE_TYPE: service_account
        FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
        FIREBASE_PRIVATE_KEY_ID: ${{secrets.FIREBASE_PRIVATE_KEY_ID}}
        FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
        FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
        FIREBASE_CLIENT_ID: ${{secrets.FIREBASE_CLIENT_ID}}
        FIREBASE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
        FIREBASE_TOKEN_URI: https://oauth2.googleapis.com/token
        FIREBASE_AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
        FIREBASE_CLIENT_X509_CERT_URL: ${{secrets.FIREBASE_CLIENT_X509_CERT_URL}}
        FIREBASE_UNIVERSE_DOMAIN: googleapis.com
        STRAVA_CLIENT_ID: ${{secrets.STRAVA_CLIENT_ID}}
        STRAVA_CLIENT_SECRET: ${{secrets.STRAVA_CLIENT_SECRET}}
        STRAVA_ACCESS_TOKEN: ${{secrets.STRAVA_ACCESS_TOKEN}}
        STRAVA_AUTH_URL: ${{secrets.STRAVA_AUTH_URL}}
        STRAVA_AUTH_SCOPE: activity:read_all
      run: |
        python -m pytest
